#!/usr/bin/env python3
"""
AI-OS Prompt Compiler
Generates system_prompt_v1.txt deterministically from modular sources.
Version: 1.0.0
"""

import argparse
import hashlib
import re
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent

SECTION_MAP = {
    "identity":       "runtime/openwebui/persona/identity.md",
    "conversation":   "runtime/openwebui/persona/conversation_style.md",
    "reasoning":      "runtime/openwebui/persona/reasoning_style.md",
    "decision":       "runtime/openwebui/persona/decision_style.md",
    "communication":  "runtime/openwebui/persona/communication_style.md",
}

MODE_MAP = {
    "coding":        "runtime/openwebui/persona/coding_mode.md",
    "architecture":  "runtime/openwebui/persona/architecture_mode.md",
    "creative":      "runtime/openwebui/persona/creative_mode.md",
    "discussion":    "runtime/openwebui/persona/discussion_mode.md",
    "professional":  "runtime/openwebui/persona/professional_mode.md",
}

CANONICAL_ORDER = [
    "identity",
    "conversation",
    "reasoning",
    "decision",
    "communication",
]


def extract_operational_content(md_text: str) -> str:
    """Extract content below the first --- separator, stripping frontmatter."""
    lines = md_text.strip().split("\n")
    # Skip YAML-style header lines and leading metadata
    in_header = True
    content_lines = []
    sep_count = 0
    for line in lines:
        if line.strip() == "---":
            sep_count += 1
            if sep_count >= 2:
                in_header = False
            continue
        if not in_header:
            content_lines.append(line)
    # If no separators found, return everything after line 1
    if in_header:
        content_lines = lines[1:]
    return "\n".join(content_lines).strip()


def validate_sources(sections: dict) -> bool:
    """Validate all source files exist and contain no placeholders."""
    all_valid = True
    for key, path_str in sections.items():
        path = REPO_ROOT / path_str
        if not path.exists():
            print(f"[ERROR] Missing source: {path_str}", file=sys.stderr)
            all_valid = False
            continue
        content = path.read_text()
        if re.search(r"TODO|PLACEHOLDER|\[TBD\]|\[FILL\]", content, re.IGNORECASE):
            print(f"[ERROR] Placeholder found in: {path_str}", file=sys.stderr)
            all_valid = False
    return all_valid


def compile_prompt(profile: str = "standard", include_mode: str = None) -> str:
    """Compile system prompt from modular sources."""
    sections = SECTION_MAP.copy()
    if not validate_sources(sections):
        raise ValueError("Source validation failed. Fix errors before compiling.")

    parts = []
    # Header comment
    parts.append(f"# AI-OS System Prompt v1")
    parts.append(f"# Profile: {profile}")
    parts.append(f"# Compiled: {datetime.utcnow().isoformat()}Z")
    parts.append(f"# DO NOT EDIT — generated by scripts/prompt_compiler/compile.py")
    parts.append("")

    # Core sections in canonical order
    for key in CANONICAL_ORDER:
        if key not in sections:
            continue
        path = REPO_ROOT / sections[key]
        content = extract_operational_content(path.read_text())
        parts.append(f"## {key.upper()}")
        parts.append(content)
        parts.append("")

    # Active mode section
    if include_mode and include_mode in MODE_MAP:
        path = REPO_ROOT / MODE_MAP[include_mode]
        content = extract_operational_content(path.read_text())
        parts.append(f"## ACTIVE MODE: {include_mode.upper()}")
        parts.append(content)
        parts.append("")

    prompt_text = "\n".join(parts)
    return prompt_text


def compute_hash(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:12]


def main():
    parser = argparse.ArgumentParser(description="AI-OS Prompt Compiler")
    parser.add_argument("--profile", default="standard",
                        choices=["standard", "coding", "architecture", "creative"],
                        help="Compilation profile")
    parser.add_argument("--mode", default=None,
                        help="Active mode to embed (coding, architecture, creative, etc.)")
    parser.add_argument("--output", default="dist/openwebui/",
                        help="Output directory")
    parser.add_argument("--validate", action="store_true",
                        help="Validate sources only; do not compile")
    parser.add_argument("--diff", action="store_true",
                        help="Show diff against previous compiled version")
    args = parser.parse_args()

    if args.validate:
        valid = validate_sources(SECTION_MAP)
        print("[PASS] All sources valid" if valid else "[FAIL] Validation failed")
        sys.exit(0 if valid else 1)

    prompt = compile_prompt(profile=args.profile, include_mode=args.mode)
    prompt_hash = compute_hash(prompt)

    out_dir = REPO_ROOT / args.output
    out_dir.mkdir(parents=True, exist_ok=True)

    out_txt = out_dir / f"system_prompt_{args.profile}.txt"
    out_txt.write_text(prompt)
    print(f"[OK] Written: {out_txt}")
    print(f"[OK] Hash: {prompt_hash}")
    print(f"[OK] Tokens (estimated): {len(prompt.split()) * 1.3:.0f}")


if __name__ == "__main__":
    main()
